### ISSUE TITLE
Show Mode Line and other highlights

### ISSUE THREAD

**Issue by timoc** [robmerrell/spacemacs_theme_gallery#6]
The mode line and search/search-replace theme is not visible. For example the difference between reverse and manoj-dark is profound when these other factors are taken into account.

**Comment by vic** [comment]
Hey, 

I was trying to htmlize the modeline in this [commit](https://github.com/vic/spacemacs_theme_gallery/commit/cfd1a4353025be1683b88016ce36b4ae21fb6dac#diff-50ef2e4fb63c8016173b8d4fc7c9673eR46), but could not get that to actually htmlize the faces. The approach was generate an string from the modeline format and insert it in a new buffer, on emacs that works just fine, but when trying to htmlize that formatted buffer I was getting an error about an invalid `quote` face. There's the branch if anyone has some insight.

Also, found that another gallery project, actually takes screenshots instead of trying to use htmlize,
maybe that's a better approach, as we could script emacs start a "heml-" command and then take the screenshot so you could see not only the sample source code, but how the modeline and helm-completions (or any other mode like org) are being colored.

https://github.com/pawelbx/emacs-theme-gallery/blob/gh-pages/elisp/emacsThemes.el#L83

**Comment by timoc** [comment]
I assume you have an X server, can i suggest you use the ```import``` command?
```
DISPLAY=:0 import -window root "$HOME/themename.png"
```
If you want to generate these without a running xserver you could also run emacs and import under ```xvfb```

**Comment by vic** [comment]
I'm running on OSX, `window-display` is `ns` (Cocoa) and generating the `htmlized` code for themes on normal buffers works as expected, except when I turn on that bit to also htmlize the content of modeline.
